/**
 * Removes empty HTML tags from generated HTML content
 * This helper is useful for cleaning up HTML generated by marked.parse()
 *
 * @param html - The HTML string to clean
 * @returns Cleaned HTML string without empty tags
 */
export function removeEmptyTagsFromGeneratedHtml(html: string): string {
  if (!html || typeof html !== 'string') {
    return html
  }

  // Remove empty tags like <p></p>, <div></div>, <span></span>, etc.
  // This regex matches tags that contain only whitespace or are completely empty
  return html.replace(/<(\w+)(?:\s[^>]*)?>\s*<\/\1>/g, '')
}
