name: Pull Request

on:
  pull_request:
    branches: [preprod]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 20
      - name: 'Install packages'
        run: yarn

      - name: 'Lint'
        run: yarn lint

      - name: 'Build'
        run: yarn build
